<link rel="stylesheet" href="./css/styleadd.css">
<section class="h-100 bg-dark">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card card-registration my-4">
            <div class="row g-0">
              <div class="col-xl-6 d-none d-xl-block">
                <img src="./img/etud1"
                  alt="Sample photo" class="img-fluid" id="img"
                  style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem; " />
              </div>
              <div class="col-xl-6">
                <form action="<?= $_SERVER['PHP_SELF'] ?>" method="post">
                <div class="card-body p-md-5 text-black">
                  <h3 class="mb-5 text-uppercase">Edit pofile </h3>
  
                  <div class="row">
                  <div class="form-outline mb-4" >
                    <label class="form-label"  for="id">id</label>
                    <input type="text" class="form-control" value="<?= $event['id'] ?>"  name="id" readonly >


                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="height">height</label>
                    <input type="text" class="form-control" value="<?= $event['height'] ?>" id="height" name="height" >

                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="Duree">active</label>
                    <input type="number" class="form-control" value="<?= $event['active'] ?>" id="active" name="active">
                  </div>
  
                  <div class="form-outline mb-4">
                    <label class="form-label" for="date_event">age </label>
                    <input type="date" class="form-control" value="<?= $event['age'] ?>" id="age" name="age">
                    
                  </div>
  
                  <div class="form-outline mb-4">
                    <label for="desc_event" class="form-label">weight</label>
                    <input type="text" class="form-control" value="<?= $event['weight'] ?>"  id="weight" name="weight" >
                  </div>

                  <div class="d-flex justify-content-end pt-3">
                    <button type="reset" class="btn btn-light btn-lg">Reset all</button>
                    <button type="submit" class="btn btn-warning btn-lg ms-2">Submit</button>
                  </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
