<link rel="stylesheet" href="./css/styleindex.css">
<section class="background-radial-gradient overflow-hidden">
        <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
        <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
        <div class="card bg-glass">
    <div class="row">
        <div class="col">
            <h1><i class="bi bi-card-checklist"></i> list of clients</h1>
        </div>
        <div class="col">
            <!-- lien de la page d'ajout -->
            <a href="add.php" class="btn btn-success float-end"><i class="bi bi-plus-square"></i> Add client programe</a>
        </div>
     </div>

     <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">height</th>
                    <th scope="col">age</th>
                    <th scope="col">weight</th>
                    <th scope="col">age</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($events as $event) : ?>
                    <tr>
                        <td class="<?= $event['height'] ?  : '' ?>"><?= $event['height'] ?></td>
                        <td class="<?= $event['age'] ?  : '' ?>"><?= $event['age'] ?></td>
                        <td class="<?= $event['weight'] ?  : '' ?>"><?= $event['weight'] ?></td>
                        <td>
                            <a href="etudiant_details.php?id=<?= $event['id']?>" class="btn btn-primary"><i class="bi bi-info-circle-fill"></i></a>
                            <!-- lien vers la page edit_todo.php -->
                            <a href="edit.php?id=<?= $event['id'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                            <!-- lien vers la page delete_todo.php -->
                            <a href="delete.php?id=<?= $event['id'] ?>" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                            
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
        </section>