<link rel="stylesheet" href="./css/styleindex.css">
<section class="background-radial-gradient overflow-hidden">
        <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
        <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
        <div class="card bg-glass">
    <div class="row">
        <div class="col">
            <h1><i class="bi bi-card-checklist"></i> your calorie</h1>
        </div>
        <div class="col">
            <!-- lien de la page d'ajout -->
            <a href="add.php" class="btn btn-success float-end"><i class="bi bi-plus-square"></i> Add client programe</a>
        </div>
     </div>

     <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">totcal</th>
                   
            </thead>
            <tbody>
            <?php foreach ($events as $event) : ?>
                    <tr>
                        <td class="<?= $event['totcal'] ?  : '' ?>"><?= $event['totcal'] ?></td>
                       
                       
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
        </section>